"""initial market schema — tickers, sectors, thematic ohlcv/features/labels

Revision ID: 0001
Revises:
Create Date: 2026-05-27

Phase 1 of the Postgres canonical-store pivot. Hand-authored (NOT
autogenerated) so this file is the canonical reference for the schema
shape — readers learn the model by reading this migration. See
docs/DESIGN-rainier-postgres-canonical-store.md §D-4 and
docs/TASK-PLAN-rainier-pg-schema-bootst-966f.md §4.

Tables (all under the ``market`` schema):

    market.tickers                  registry
    market.sectors                  registry
    market.thematic_ohlcv           raw daily OHLCV
    market.thematic_features_daily  Layer-A features (FKs → registries)
    market.thematic_labels_daily    Layer-B forward returns

ASCII dependency graph (drop in reverse for downgrade):

    tickers ────┐
                ├──► thematic_features_daily
    sectors ────┘

    thematic_ohlcv          (standalone)
    thematic_labels_daily   (standalone)
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import DOUBLE_PRECISION, REAL, TIMESTAMP

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SCHEMA = "market"


def upgrade() -> None:
    """Create the market schema + 5 tables + indexes."""
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA}")

    # ---- market.tickers ---------------------------------------------------
    op.create_table(
        "tickers",
        sa.Column("ticker_id", sa.SmallInteger, primary_key=True),
        sa.Column("symbol", sa.Text, nullable=False, unique=True),
        sa.Column("first_seen", sa.Date, nullable=False),
        sa.Column("last_seen", sa.Date, nullable=True),
        schema=SCHEMA,
    )

    # ---- market.sectors ---------------------------------------------------
    op.create_table(
        "sectors",
        sa.Column("sector_id", sa.SmallInteger, primary_key=True),
        sa.Column("sector_name", sa.Text, nullable=False, unique=True),
        sa.Column("first_seen", sa.Date, nullable=False),
        schema=SCHEMA,
    )

    # ---- market.thematic_ohlcv -------------------------------------------
    op.create_table(
        "thematic_ohlcv",
        sa.Column("symbol", sa.Text, nullable=False),
        sa.Column("date", sa.Date, nullable=False),
        sa.Column("open", DOUBLE_PRECISION, nullable=False),
        sa.Column("high", DOUBLE_PRECISION, nullable=False),
        sa.Column("low", DOUBLE_PRECISION, nullable=False),
        sa.Column("close", DOUBLE_PRECISION, nullable=False),
        sa.Column("volume", sa.BigInteger, nullable=False),
        sa.Column("fetched_at", TIMESTAMP(timezone=True), nullable=False),
        sa.Column("yfinance_version", sa.Text, nullable=False),
        sa.PrimaryKeyConstraint("symbol", "date", name="thematic_ohlcv_pkey"),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_thematic_ohlcv_date",
        "thematic_ohlcv",
        ["date"],
        schema=SCHEMA,
    )

    # ---- market.thematic_features_daily ----------------------------------
    op.create_table(
        "thematic_features_daily",
        sa.Column("asof_date", sa.Date, nullable=False),
        sa.Column("symbol", sa.Text, nullable=False),
        sa.Column(
            "ticker_id",
            sa.SmallInteger,
            sa.ForeignKey(f"{SCHEMA}.tickers.ticker_id"),
            nullable=False,
        ),
        sa.Column(
            "sector_id",
            sa.SmallInteger,
            sa.ForeignKey(f"{SCHEMA}.sectors.sector_id"),
            nullable=False,
        ),
        sa.Column("close", DOUBLE_PRECISION, nullable=False),
        sa.Column("ret_1d", REAL, nullable=True),
        sa.Column("rel_5", REAL, nullable=True),
        sa.Column("rel_10", REAL, nullable=True),
        sa.Column("rel_20", REAL, nullable=True),
        sa.Column("ret_ytd", REAL, nullable=True),
        sa.Column("relvol_5", REAL, nullable=True),
        sa.Column("relvol_10", REAL, nullable=True),
        sa.Column("relvol_20", REAL, nullable=True),
        sa.Column("r_5", sa.SmallInteger, nullable=True),
        sa.Column("r_10", sa.SmallInteger, nullable=True),
        sa.Column("r_20", sa.SmallInteger, nullable=True),
        sa.Column("rank", sa.SmallInteger, nullable=False),
        sa.Column("rank_delta_1d", sa.SmallInteger, nullable=False),
        sa.Column("rank_delta_5d", sa.SmallInteger, nullable=False),
        sa.Column("top15_streak", sa.SmallInteger, nullable=False),
        sa.Column("rank_minus_sector_mean", REAL, nullable=True),
        sa.Column("universe_size", sa.SmallInteger, nullable=False),
        sa.Column("universe_yaml_sha", sa.Text, nullable=False),
        sa.Column("computed_at", TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint(
            "asof_date", "symbol", name="thematic_features_daily_pkey"
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_thematic_features_daily_asof_date",
        "thematic_features_daily",
        ["asof_date"],
        schema=SCHEMA,
    )

    # ---- market.thematic_labels_daily ------------------------------------
    op.create_table(
        "thematic_labels_daily",
        sa.Column("asof_date", sa.Date, nullable=False),
        sa.Column("symbol", sa.Text, nullable=False),
        sa.Column("fwd_3d_ret", REAL, nullable=True),
        sa.Column("fwd_5d_ret", REAL, nullable=True),
        sa.Column("fwd_10d_ret", REAL, nullable=True),
        sa.Column("fwd_20d_ret", REAL, nullable=True),
        sa.Column("fwd_30d_ret", REAL, nullable=True),
        sa.Column("fwd_5d_excess_ret", REAL, nullable=True),
        sa.Column("fwd_10d_excess_ret", REAL, nullable=True),
        sa.Column("fwd_20d_excess_ret", REAL, nullable=True),
        sa.Column("fwd_10d_max_drawdown", REAL, nullable=True),
        sa.Column("fwd_10d_max_runup", REAL, nullable=True),
        sa.Column("label_complete_through", sa.Date, nullable=False),
        sa.PrimaryKeyConstraint(
            "asof_date", "symbol", name="thematic_labels_daily_pkey"
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_thematic_labels_daily_asof_date",
        "thematic_labels_daily",
        ["asof_date"],
        schema=SCHEMA,
    )


# Tables this revision's upgrade() created, in reverse dependency order so a
# non-cascading DROP TABLE works: our own FK (thematic_features_daily → tickers,
# sectors) is gone before its parents are dropped. We deliberately do NOT pass
# CASCADE — a plain DROP TABLE removes the table's own indexes/constraints but
# RESTRICTs against *foreign* dependents (a non-rainier view/FK/materialized
# view over one of these tables), failing loudly instead of silently destroying
# them. That loud failure is the correct outcome in the multi-writer scenario
# this revision's downgrade is meant to protect: the operator sees the foreign
# dependency and resolves it rather than losing it.
#
#     thematic_features_daily ──FK──► tickers, sectors   (drop dependent first)
#     thematic_ohlcv          (standalone)
#     thematic_labels_daily   (standalone)
_REVISION_TABLES = (
    "thematic_features_daily",
    "thematic_labels_daily",
    "thematic_ohlcv",
    "tickers",
    "sectors",
)


def downgrade() -> None:
    """Reverse this revision without wiping foreign objects.

    The original implementation issued an unconditional
    ``DROP SCHEMA market CASCADE``. That is safe only while rainier solely owns
    ``market``; the moment the schema holds a non-rainier object (a future
    multi-writer deployment), a ``downgrade base`` would silently destroy it.

    Guarded reversal:

      1. Drop only the 5 tables THIS revision's ``upgrade()`` created, in
         reverse dependency order with NON-cascading ``DROP TABLE``. A plain
         drop removes each table's own indexes/constraints but RESTRICTs
         against foreign dependents (a non-rainier view/FK over one of these
         tables), so the downgrade fails loudly rather than silently dropping
         or mutating a foreign object. CASCADE is intentionally NOT used.
      2. Drop the ``market`` schema only if it is now empty. If any foreign
         object remains, leave the (now rainier-free) schema in place. Using
         ``DROP SCHEMA ... RESTRICT`` (no CASCADE) is the belt-and-suspenders
         guard — even a logic error in the emptiness check cannot wipe a
         populated schema, because RESTRICT refuses to drop a non-empty schema.

    The ``alembic_version`` table lives in ``public`` (see env.py), so it
    survives regardless.
    """
    for table in _REVISION_TABLES:
        op.execute(f"DROP TABLE IF EXISTS {SCHEMA}.{table} RESTRICT")

    # Drop the schema only when nothing else lives in it. RESTRICT makes the
    # DROP a no-op-or-error against a populated schema; we gate on the object
    # count so it's a clean no-op (foreign objects survive) rather than a
    # raised error that would abort the downgrade.
    #
    # Probe pg_class (tables, views, sequences, materialized views, indexes),
    # pg_proc (functions/procedures), and pg_type (user-defined types). A
    # tables-only check (information_schema.tables) would miss a foreign
    # sequence/function/type, letting the RESTRICT drop raise and abort the
    # downgrade. Dropping our 5 tables above also removed their auto-created
    # composite rowtypes, array types, and indexes (verified: a clean schema
    # has zero rows across all three catalogs), so any remaining row here is a
    # foreign object and the schema must be left in place.
    op.execute(
        f"""
        DO $$
        DECLARE
            ns oid;
            obj_count integer;
        BEGIN
            SELECT oid INTO ns FROM pg_namespace WHERE nspname = '{SCHEMA}';
            IF ns IS NULL THEN
                RETURN;  -- schema already gone (idempotent downgrade)
            END IF;

            SELECT
                (SELECT count(*) FROM pg_class WHERE relnamespace = ns)
              + (SELECT count(*) FROM pg_proc  WHERE pronamespace = ns)
              + (SELECT count(*) FROM pg_type  WHERE typnamespace = ns)
            INTO obj_count;

            IF obj_count = 0 THEN
                EXECUTE 'DROP SCHEMA IF EXISTS {SCHEMA} RESTRICT';
            END IF;
        END $$;
        """
    )
