"""fix two schema seams for the dual-write writers

Revision ID: 0002
Revises: 0001
Create Date: 2026-05-27

Phase 2 of the Postgres canonical-store pivot folds in the
``market-schema-writer-sea-78b3`` seam fixes (task plan §3). Two changes the
feature/label writers need before they can dual-write:

  1. ``market.thematic_features_daily`` — ADD ``trading_day_ordinal`` (Integer,
     nullable). The feature compute emits an int32 panel-relative ordinal;
     0001 dropped it but the writer mirrors the parquet shape. Nullable
     because the value is provenance (shifts on re-backfill), not a key, and
     short backfills may omit it.

  2. ``market.thematic_labels_daily`` — relax ``label_complete_through`` from
     NOT NULL to nullable. A panel too short to complete any forward horizon
     produces valid rows with a NULL completion date.

Hand-authored (NOT autogenerated), following the 0001 pattern so the file
stays a readable canonical reference. Both ``upgrade()`` and ``downgrade()``
are reversible.

ASCII (forward = upgrade, reverse = downgrade):

    features:  + trading_day_ordinal (int, null)   <->   drop column
    labels:    label_complete_through  NOT NULL->NULL <-> set NOT NULL
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SCHEMA = "market"


def upgrade() -> None:
    """Add trading_day_ordinal; relax label_complete_through to nullable."""
    op.add_column(
        "thematic_features_daily",
        sa.Column("trading_day_ordinal", sa.Integer(), nullable=True),
        schema=SCHEMA,
    )
    op.alter_column(
        "thematic_labels_daily",
        "label_complete_through",
        existing_type=sa.Date(),
        nullable=True,
        schema=SCHEMA,
    )


def downgrade() -> None:
    """Reverse: drop the column; re-tighten label_complete_through to NOT NULL.

    NOTE: the downgrade re-tightens label_complete_through to NOT NULL. If
    rows with a NULL value exist (written during the dual-write era), this
    will fail — which is the correct, loud behavior: a downgrade that would
    silently drop or mangle data should refuse. The operator backfills or
    deletes the NULL rows before downgrading.
    """
    op.alter_column(
        "thematic_labels_daily",
        "label_complete_through",
        existing_type=sa.Date(),
        nullable=False,
        schema=SCHEMA,
    )
    op.drop_column(
        "thematic_features_daily",
        "trading_day_ordinal",
        schema=SCHEMA,
    )
