"""backup.money_flow_snapshots — off-machine money-flow durability backup

Revision ID: 0004
Revises: 0003
Create Date: 2026-06-02

money-flow-neon-backup-b613 (P2): the QU100 money-flow history lives only on the
local TimescaleDB and is irreplaceable (QU's date-keyed endpoint has no replay).
This migration creates a plain-table backup on Neon so a managed off-machine
copy exists. Local TimescaleDB stays the primary; this is a backup, not a query
surface.

HAND-WRITTEN (NOT autogenerated): env.py:_include_only_market scopes autogenerate
to the ``market`` schema, so it would never manage a ``backup.*`` table — same as
it doesn't manage ``public``. This is intentional; the backup table mirrors
core/models.py:MoneyFlowSnapshot column-for-column and is maintained by hand.

Design choices (DESIGN-money-flow-neon-backup.md §2.1):
  * Separate ``backup`` schema isolates the backup from the ``market.*``
    research data and the legacy ``public`` tables.
  * COMPOSITE PK (id, captured_at) mirrors the SOURCE exactly — at the source
    ``id`` alone is NOT DB-enforced-unique (the PK is composite for the
    TimescaleDB partition), so the backup must not assume it. The copy uses
    ON CONFLICT (id, captured_at) DO NOTHING against this PK.
  * NO foreign key to ``stocks`` — the backup table is standalone (an FK would
    require backing up ``stocks`` too, out of scope; restore §5 accounts for it).
  * Plain table, NOT a TimescaleDB hypertable (backup, not a query surface).
  * Index on (data_date, ranking_type) for ad-hoc restore queries.

ASCII (forward = upgrade, reverse = downgrade):

    + CREATE SCHEMA backup            <->   DROP SCHEMA backup CASCADE
    + backup.money_flow_snapshots     <->   drop table (with the schema)

Downgrade owns ONLY the ``backup`` schema it created — it never touches
``market`` (0001-0003) or ``public``.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB, TIMESTAMP

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SCHEMA = "backup"


def upgrade() -> None:
    """Create the ``backup`` schema + backup.money_flow_snapshots (plain table)."""
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA}")

    op.create_table(
        "money_flow_snapshots",
        # Mirrors core/models.py:MoneyFlowSnapshot columns exactly.
        sa.Column("id", sa.BigInteger, nullable=False),
        sa.Column("captured_at", TIMESTAMP(timezone=True), nullable=False),
        sa.Column("capture_session", sa.String(20), nullable=False),
        sa.Column("data_date", sa.Date, nullable=False),
        sa.Column("view_type", sa.String(10), nullable=False),
        sa.Column("ranking_type", sa.String(10), nullable=False),
        sa.Column("symbol", sa.String(10), nullable=False),
        sa.Column("rank", sa.Integer, nullable=False),
        sa.Column("daily_change", sa.Integer, nullable=True),
        sa.Column("sector", sa.String(100), nullable=True),
        sa.Column("industry", sa.String(200), nullable=True),
        sa.Column("long_short", sa.String(50), nullable=True),
        # JSONB (not text): raw_data is bound as a dict by the typed Core insert.
        sa.Column("raw_data", JSONB, nullable=True),
        # Composite PK mirrors the source (id alone is NOT DB-unique at source).
        sa.PrimaryKeyConstraint(
            "id", "captured_at", name="backup_money_flow_snapshots_pkey"
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_backup_money_flow_snapshots_data_date_ranking_type",
        "money_flow_snapshots",
        ["data_date", "ranking_type"],
        schema=SCHEMA,
    )


def downgrade() -> None:
    """Drop backup.money_flow_snapshots + the ``backup`` schema.

    0004 owns ONLY the ``backup`` schema, so dropping it (CASCADE removes the
    table + index) is safe and does NOT touch ``market`` (0001-0003) or
    ``public``. Unlike 0001's guarded market downgrade, ``backup`` is exclusively
    this revision's, so the unconditional cascade is appropriate here.
    """
    op.execute(f"DROP SCHEMA IF EXISTS {SCHEMA} CASCADE")
